[workspace]
dependencies_update = true
changelog_update = true
git_release_enable = true
git_tag_enable = true
publish = false

[[package]]
name = "inbx-core"
[[package]]
name = "inbx-net"
[[package]]
name = "inbx-store"
[[package]]
name = "inbx-config"
[[package]]
name = "inbx-render"
[[package]]
name = "inbx-contacts"
[[package]]
name = "inbx-ical"
[[package]]
name = "inbx-composer"
[[package]]
name = "inbx"
